# Site settings
title: Tom Deakin
email: tom@tomdeakin.com
description: > # this means to ignore newlines until "baseurl:"
  Trumpet and Natural Trumpet Player. Computer Scientist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tomdeakin.com" # the base hostname & protocol for your site
twitter_username: tjdeakin
facebook_username: tomdeakin
github_username:  tomdeakin

# Build settings
markdown: kramdown
highlighter: pygments

# Auto build a sitemap
gems:
  - jekyll-sitemap

